<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="NewFolder1\**" />
    <Compile Remove="NewFolder\**" />
    <Content Remove="NewFolder1\**" />
    <Content Remove="NewFolder\**" />
    <EmbeddedResource Remove="NewFolder1\**" />
    <EmbeddedResource Remove="NewFolder\**" />
    <None Remove="NewFolder1\**" />
    <None Remove="NewFolder\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Controllers\detailController.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Views\Shared\Error.cshtml" />
    <None Include="Views\Shared\_Layout.cshtml" />
    <None Include="Views\Shared\_ValidationScriptsPartial.cshtml" />
    <None Include="wwwroot\assets\css\argon-dashboard-tailwind.css" />
    <None Include="wwwroot\assets\css\argon-dashboard-tailwind.min.css" />
    <None Include="wwwroot\assets\css\nucleo-icons.css" />
    <None Include="wwwroot\assets\css\nucleo-svg.css" />
    <None Include="wwwroot\assets\css\perfect-scrollbar.css" />
    <None Include="wwwroot\assets\css\tooltips.css" />
    <None Include="wwwroot\assets\fonts\nucleo-icons.eot" />
    <None Include="wwwroot\assets\fonts\nucleo-icons.svg" />
    <None Include="wwwroot\assets\fonts\nucleo-icons.ttf" />
    <None Include="wwwroot\assets\fonts\nucleo-icons.woff" />
    <None Include="wwwroot\assets\fonts\nucleo-icons.woff2" />
    <None Include="wwwroot\assets\fonts\nucleo.eot" />
    <None Include="wwwroot\assets\fonts\nucleo.ttf" />
    <None Include="wwwroot\assets\fonts\nucleo.woff" />
    <None Include="wwwroot\assets\fonts\nucleo.woff2" />
    <None Include="wwwroot\assets\img\apple-icon.png" />
    <None Include="wwwroot\assets\img\bg-profile.jpg" />
    <None Include="wwwroot\assets\img\bg1.jpg" />
    <None Include="wwwroot\assets\img\bruce-mars.jpg" />
    <None Include="wwwroot\assets\img\carousel-1.jpg" />
    <None Include="wwwroot\assets\img\carousel-2.jpg" />
    <None Include="wwwroot\assets\img\carousel-3.jpg" />
    <None Include="wwwroot\assets\img\curved-images\curved-10.jpg" />
    <None Include="wwwroot\assets\img\curved-images\curved-11.jpg" />
    <None Include="wwwroot\assets\img\curved-images\curved-6.jpg" />
    <None Include="wwwroot\assets\img\curved-images\curved-8.jpg" />
    <None Include="wwwroot\assets\img\curved-images\curved0.jpg" />
    <None Include="wwwroot\assets\img\curved-images\curved1.jpg" />
    <None Include="wwwroot\assets\img\curved-images\curved10.jpg" />
    <None Include="wwwroot\assets\img\curved-images\curved11-small.jpg" />
    <None Include="wwwroot\assets\img\curved-images\curved11.jpg" />
    <None Include="wwwroot\assets\img\curved-images\curved12.jpg" />
    <None Include="wwwroot\assets\img\curved-images\curved13.jpg" />
    <None Include="wwwroot\assets\img\curved-images\curved14.jpg" />
    <None Include="wwwroot\assets\img\curved-images\curved19.jpg" />
    <None Include="wwwroot\assets\img\curved-images\curved2.jpg" />
    <None Include="wwwroot\assets\img\curved-images\curved21.jpg" />
    <None Include="wwwroot\assets\img\curved-images\curved3.jpg" />
    <None Include="wwwroot\assets\img\curved-images\curved4.jpg" />
    <None Include="wwwroot\assets\img\curved-images\curved5-small.jpg" />
    <None Include="wwwroot\assets\img\curved-images\curved5.jpg" />
    <None Include="wwwroot\assets\img\curved-images\curved6-small.jpg" />
    <None Include="wwwroot\assets\img\curved-images\curved6.jpg" />
    <None Include="wwwroot\assets\img\curved-images\curved7.jpg" />
    <None Include="wwwroot\assets\img\curved-images\curved8.jpg" />
    <None Include="wwwroot\assets\img\curved-images\curved9.jpg" />
    <None Include="wwwroot\assets\img\curved-images\white-curved.jpeg" />
    <None Include="wwwroot\assets\img\down-arrow-dark.svg" />
    <None Include="wwwroot\assets\img\down-arrow-white.svg" />
    <None Include="wwwroot\assets\img\down-arrow.svg" />
    <None Include="wwwroot\assets\img\favicon.png" />
    <None Include="wwwroot\assets\img\hamza-pp.jpeg" />
    <None Include="wwwroot\assets\img\home-decor-1.jpg" />
    <None Include="wwwroot\assets\img\home-decor-2.jpg" />
    <None Include="wwwroot\assets\img\home-decor-3.jpg" />
    <None Include="wwwroot\assets\img\house.jpg" />
    <None Include="wwwroot\assets\img\icons\flags\AU.png" />
    <None Include="wwwroot\assets\img\icons\flags\BR.png" />
    <None Include="wwwroot\assets\img\icons\flags\DE.png" />
    <None Include="wwwroot\assets\img\icons\flags\GB.png" />
    <None Include="wwwroot\assets\img\icons\flags\US.png" />
    <None Include="wwwroot\assets\img\illustrations\icon-documentation.svg" />
    <None Include="wwwroot\assets\img\illustrations\rocket-white.png" />
    <None Include="wwwroot\assets\img\ivana-square.jpg" />
    <None Include="wwwroot\assets\img\ivancik.jpg" />
    <None Include="wwwroot\assets\img\kal-visuals-square.jpg" />
    <None Include="wwwroot\assets\img\logo-ct-dark.png" />
    <None Include="wwwroot\assets\img\logo-ct.png" />
    <None Include="wwwroot\assets\img\logos\mastercard.png" />
    <None Include="wwwroot\assets\img\logos\visa.png" />
    <None Include="wwwroot\assets\img\marie.jpg" />
    <None Include="wwwroot\assets\img\shapes\pattern-lines.svg" />
    <None Include="wwwroot\assets\img\shapes\shape-1.svg" />
    <None Include="wwwroot\assets\img\shapes\shape-2.svg" />
    <None Include="wwwroot\assets\img\shapes\shape-3.svg" />
    <None Include="wwwroot\assets\img\shapes\wave-down.svg" />
    <None Include="wwwroot\assets\img\shapes\wave-up.svg" />
    <None Include="wwwroot\assets\img\shapes\waves-gray.svg" />
    <None Include="wwwroot\assets\img\shapes\waves-white.svg" />
    <None Include="wwwroot\assets\img\small-logos\icon-sun-cloud.png" />
    <None Include="wwwroot\assets\img\small-logos\logo-atlassian.svg" />
    <None Include="wwwroot\assets\img\small-logos\logo-invision.svg" />
    <None Include="wwwroot\assets\img\small-logos\logo-jira.svg" />
    <None Include="wwwroot\assets\img\small-logos\logo-slack.svg" />
    <None Include="wwwroot\assets\img\small-logos\logo-spotify.svg" />
    <None Include="wwwroot\assets\img\small-logos\logo-webdev.svg" />
    <None Include="wwwroot\assets\img\small-logos\logo-xd.svg" />
    <None Include="wwwroot\assets\img\team-1.jpg" />
    <None Include="wwwroot\assets\img\team-2.jpg" />
    <None Include="wwwroot\assets\img\team-3.jpg" />
    <None Include="wwwroot\assets\img\team-4.jpg" />
    <None Include="wwwroot\assets\img\theme\angular.jpg" />
    <None Include="wwwroot\assets\img\theme\bootstrap.jpg" />
    <None Include="wwwroot\assets\img\theme\dribbble.png" />
    <None Include="wwwroot\assets\img\theme\dropbox.png" />
    <None Include="wwwroot\assets\img\theme\mastercard.png" />
    <None Include="wwwroot\assets\img\theme\paypal.png" />
    <None Include="wwwroot\assets\img\theme\react.jpg" />
    <None Include="wwwroot\assets\img\theme\sketch.jpg" />
    <None Include="wwwroot\assets\img\theme\slack.png" />
    <None Include="wwwroot\assets\img\theme\spotify.jpeg" />
    <None Include="wwwroot\assets\img\theme\tim.png" />
    <None Include="wwwroot\assets\img\theme\unass.jpg" />
    <None Include="wwwroot\assets\img\theme\visa.png" />
    <None Include="wwwroot\assets\img\theme\vue.jpg" />
    <None Include="wwwroot\assets\img\vr-bg.jpg" />
    <None Include="wwwroot\assets\js\argon-dashboard-tailwind.js" />
    <None Include="wwwroot\assets\js\argon-dashboard-tailwind.min.js" />
    <None Include="wwwroot\assets\js\carousel.js" />
    <None Include="wwwroot\assets\js\charts.js" />
    <None Include="wwwroot\assets\js\dropdown.js" />
    <None Include="wwwroot\assets\js\fixed-plugin.js" />
    <None Include="wwwroot\assets\js\nav-pills.js" />
    <None Include="wwwroot\assets\js\navbar-collapse.js" />
    <None Include="wwwroot\assets\js\navbar-sticky.js" />
    <None Include="wwwroot\assets\js\perfect-scrollbar.js" />
    <None Include="wwwroot\assets\js\plugins\Chart.extension.js" />
    <None Include="wwwroot\assets\js\plugins\chartjs.min.js" />
    <None Include="wwwroot\assets\js\plugins\perfect-scrollbar.min.js" />
    <None Include="wwwroot\assets\js\sidenav-burger.js" />
    <None Include="wwwroot\assets\js\tooltips.js" />
    <None Include="wwwroot\css\detayCss\add-to-cart.min.js.indir" />
    <None Include="wwwroot\css\detayCss\anti-spam.js.indir" />
    <None Include="wwwroot\css\detayCss\browser-check.js.indir" />
    <None Include="wwwroot\css\detayCss\cart-fragments.min.js.indir" />
    <None Include="wwwroot\css\detayCss\client" />
    <None Include="wwwroot\css\detayCss\comment-reply.min.js.indir" />
    <None Include="wwwroot\css\detayCss\common.js.indir" />
    <None Include="wwwroot\css\detayCss\core.min.js.indir" />
    <None Include="wwwroot\css\detayCss\css" />
    <None Include="wwwroot\css\detayCss\custom-marker.js.indir" />
    <None Include="wwwroot\css\detayCss\google-map.js.indir" />
    <None Include="wwwroot\css\detayCss\gsap.min.js.indir" />
    <None Include="wwwroot\css\detayCss\gtm.js.indir" />
    <None Include="wwwroot\css\detayCss\hoverIntent.min.js.indir" />
    <None Include="wwwroot\css\detayCss\index%281%29.js.indir" />
    <None Include="wwwroot\css\detayCss\index.js.indir" />
    <None Include="wwwroot\css\detayCss\isotope.pkgd.min.js.indir" />
    <None Include="wwwroot\css\detayCss\jquery-migrate.min.js.indir" />
    <None Include="wwwroot\css\detayCss\jquery.blockUI.min.js.indir" />
    <None Include="wwwroot\css\detayCss\jquery.magnific-popup.min.js.indir" />
    <None Include="wwwroot\css\detayCss\jquery.min.js.indir" />
    <None Include="wwwroot\css\detayCss\jquery.parallax-scroll.js.indir" />
    <None Include="wwwroot\css\detayCss\js" />
    <None Include="wwwroot\css\detayCss\js.cookie.min.js.indir" />
    <None Include="wwwroot\css\detayCss\logo-mobile.svg" />
    <None Include="wwwroot\css\detayCss\logo.svg" />
    <None Include="wwwroot\css\detayCss\main.js.indir" />
    <None Include="wwwroot\css\detayCss\main.min%281%29.js.indir" />
    <None Include="wwwroot\css\detayCss\main.min.js.indir" />
    <None Include="wwwroot\css\detayCss\markerclusterer.js.indir" />
    <None Include="wwwroot\css\detayCss\matterport-logo.svg" />
    <None Include="wwwroot\css\detayCss\modernizr.js.indir" />
    <None Include="wwwroot\css\detayCss\newhome-core.min.js.indir" />
    <None Include="wwwroot\css\detayCss\newhome-membership.min.js.indir" />
    <None Include="wwwroot\css\detayCss\nouislider.min.js.indir" />
    <None Include="wwwroot\css\detayCss\packery-mode.pkgd.min.js.indir" />
    <None Include="wwwroot\css\detayCss\rbt-modules.js.indir" />
    <None Include="wwwroot\css\detayCss\rbtools.min.js.indir" />
    <None Include="wwwroot\css\detayCss\rs6.min.js.indir" />
    <None Include="wwwroot\css\detayCss\sdk%281%29.js.indir" />
    <None Include="wwwroot\css\detayCss\sdk.js.indir" />
    <None Include="wwwroot\css\detayCss\select2.full.min.js.indir" />
    <None Include="wwwroot\css\detayCss\showcase.js.indir" />
    <None Include="wwwroot\css\detayCss\snippet.js.indir" />
    <None Include="wwwroot\css\detayCss\swiper.min.js.indir" />
    <None Include="wwwroot\css\detayCss\tabs.min.js.indir" />
    <None Include="wwwroot\css\detayCss\three.min.js.indir" />
    <None Include="wwwroot\css\detayCss\underscore.min.js.indir" />
    <None Include="wwwroot\css\detayCss\util.js.indir" />
    <None Include="wwwroot\css\detayCss\woocommerce.min.js.indir" />
    <None Include="wwwroot\css\detayCss\wp-emoji-release.min.js.indir" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="11.11.0" />
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BusinesLayer\BusinesLayer.csproj" />
    <ProjectReference Include="..\DataAccessLayer\DataAccessLayer.csproj" />
    <ProjectReference Include="..\EntityLayer\EntityLayer.csproj" />
  </ItemGroup>

</Project>
