// <auto-generated />
using DataAccessLayer.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20241015114613_mig2")]
    partial class mig2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EntityLayer.Concrete.BolgeMahalle", b =>
                {
                    b.Property<int>("BolgeMahalleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BolgeMahalleID"));

                    b.Property<string>("BolgeMahalleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BolgeMahalleID");

                    b.ToTable("BolgeMahalles");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Emlak", b =>
                {
                    b.Property<int>("EmlakID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmlakID"));

                    b.Property<int>("BolgeMahalleID")
                        .HasColumnType("int");

                    b.Property<string>("EmlakAciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmlakAsansor")
                        .HasColumnType("bit");

                    b.Property<bool>("EmlakEsya")
                        .HasColumnType("bit");

                    b.Property<string>("EmlakIsitma")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmlakKat")
                        .HasColumnType("int");

                    b.Property<int>("EmlakMetreKare")
                        .HasColumnType("int");

                    b.Property<string>("EmlakName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmlakOda")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmlakOtopark")
                        .HasColumnType("bit");

                    b.Property<bool>("EmlakYayinda")
                        .HasColumnType("bit");

                    b.HasKey("EmlakID");

                    b.HasIndex("BolgeMahalleID");

                    b.ToTable("Emlaks");
                });

            modelBuilder.Entity("EntityLayer.Concrete.EmlakTip", b =>
                {
                    b.Property<int>("EmlakTipID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmlakTipID"));

                    b.Property<string>("EmlakTipName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmlakTipID");

                    b.ToTable("EmlakTips");
                });

            modelBuilder.Entity("EntityLayer.Concrete.EmlakTur", b =>
                {
                    b.Property<int>("EmlakTurID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmlakTurID"));

                    b.Property<string>("EmlakTurName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmlakTurID");

                    b.ToTable("EmlakTurs");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Yonetici", b =>
                {
                    b.Property<int>("YoneticiID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("YoneticiID"));

                    b.Property<string>("YoneticiAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YoneticiMail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YoneticiSoyadi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YoneticiTel")
                        .HasColumnType("int");

                    b.Property<string>("YoneticiUnvan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("YoneticiID");

                    b.ToTable("Yoneticis");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Emlak", b =>
                {
                    b.HasOne("EntityLayer.Concrete.BolgeMahalle", "BolgeMahalle")
                        .WithMany("Emlaks")
                        .HasForeignKey("BolgeMahalleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BolgeMahalle");
                });

            modelBuilder.Entity("EntityLayer.Concrete.BolgeMahalle", b =>
                {
                    b.Navigation("Emlaks");
                });
#pragma warning restore 612, 618
        }
    }
}
